### ISSUE TITLE
Assignment 2 Ready for Grading

### ISSUE THREAD

**Issue by adriana-lh** [SES-5215-F2020/alassoharrier-quant#2]
Hello, 

Assignment 2 has been uploaded and is now ready for grading. 
You can view my assignment at this link: https://ses-5215-f2020.github.io/alassoharrier-quant/Assignment-2

Thank you!

**Comment by c-voulgaris** [comment]
This looks great!

On line 175: What's happening here is that it's showing the variable names one after another in rows, but it only shows the number at the beginning of the row. So if you had twelve different values, and the 8th one wrapped onto the next row, there'd be an [8] at the beginning of the row, and you wouldn't see any of the other numbers. This is fine.

You can still take the same approach you took for the foreign-born variable. It would look like this:

```
asian <- t.test(MA_tracts$maj_race == "asian")
black <- t.test(MA_tracts$maj_race == "black")
latino <- t.test(MA_tracts$maj_race == "latino")
`no majority` <- t.test(MA_tracts$maj_race == "no_majority")
white <- t.test(MA_tracts$maj_race == "white")

tract_for <- tibble(`Majority race` = c("White", "Black", "Latino", "Asian", "No majority"), 
                     `Sample proportion` =
                       c(paste(prettyNum(white$estimate*100,
                                         digits = 3), "%"),
                         paste(prettyNum(black$estimate*100,
                                         digits = 3), "%"),
                         paste(prettyNum(latino$estimate*100,
                                         digits = 3), "%"),
                         paste(prettyNum(asian$estimate*100,
                                         digits = 3), "%"),
                         paste(prettyNum(`no majority`$estimate*100,
                                         digits = 3), "%")),
```
and so on...
