### ISSUE TITLE
Assignment 3 is Ready for Grading

### ISSUE THREAD

**Issue by adriana-lh** [SES-5215-F2020/alassoharrier-quant#3]
You can view assignment 3 at this link: https://ses-5215-f2020.github.io/alassoharrier-quant/Assignment-3

Thank you!

**Comment by saratepfer** [comment]
Nice job on this, Adriana! Please see a few comments below:

- it's not required for the assignment, but it would be great if you could brainstorm/show ways to visualize the results of the chi-squared test.
- The y-axis on your percent internet/majority race box plot shows decimal values with % signs. I would multiply the values by 100 for clarity.
- For test 1 of your two-sample t-tests, your description references medians when it should refer to means.
